// src/App.js
//
// import React from 'react';
// import './App.css';
//
// function App() {
//   return (
//       <div className="min-h-screen bg-gray-100">
//             {/* 导航栏 */}
//                   <nav className="bg-black text-white p-6">
//                           <div className="container mx-auto flex items-center justify-between">
//                                     <h1 className="font-bold text-2xl">工作室名称</h1>
//                                               <ul className="flex space-x-8">
//                                                           <li><a href="#intro" className="hover:underline">介绍</a></li>
//                                                                       <li><a href="#services" className="hover:underline">服务</a></li>
//                                                                                   <li><a href="#contact" className="hover:underline">联系我们</a></li>
//                                                                                             </ul>
//                                                                                                     </div>
//                                                                                                           </nav>
//
//                                                                                                                 {/* 介绍区域 */}
//                                                                                                                       <div className="relative bg-no-repeat bg-cover" style={{backgroundImage: 'url("your-background-image.jpg")'}} id="intro">
//                                                                                                                               <div className="absolute inset-0 bg-black/50" />
//                                                                                                                                       <div className="container mx-auto p-20 text-center">
//                                                                                                                                                 <h2 className="text-4xl font-bold text-white">欢迎来到我们的工作室</h2>
//                                                                                                                                                           <p className="text-xl text-white">我们专注于创造令人惊叹的设计和开发解决方案。</p>
//                                                                                                                                                                   </div>
//                                                                                                                                                                         </div>
//
//                                                                                                                                                                               {/* 服务列表 */}
//                                                                                                                                                                                     <div className="container mx-auto py-20" id="services">
//                                                                                                                                                                                             <h2 className="text-3xl font-bold text-center mb-10">我们的服务</h2>
//                                                                                                                                                                                                     <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
//                                                                                                                                                                                                               <div className="bg-white p-8 rounded-lg shadow">
//                                                                                                                                                                                                                           <h3 className="text-xl font-bold mb-2">服务1</h3>
//                                                                                                                                                                                                                                       <p>服务描述...</p>
//                                                                                                                                                                                                                                                 </div>
//                                                                                                                                                                                                                                                           {/* 复制上面的div来添加更多服务 */}
//                                                                                                                                                                                                                                                                   </div>
//                                                                                                                                                                                                                                                                         </div>
//
//                                                                                                                                                                                                                                                                               {/* 联系表单 */}
//                                                                                                                                                                                                                                                                                     <div className="container mx-auto py-20" id="contact">
//                                                                                                                                                                                                                                                                                             <h2 className="text-3xl font-bold text-center mb-10">联系我们</h2>
//                                                                                                                                                                                                                                                                                                     <form className="w-full max-w-lg mx-auto">
//                                                                                                                                                                                                                                                                                                               <div className="flex flex-wrap -mx-3 mb-6">
//                                                                                                                                                                                                                                                                                                                           <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
//                                                                                                                                                                                                                                                                                                                                         <label className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" htmlFor="grid-first-name">
//                                                                                                                                                                                                                                                                                                                                                         名字
//                                                                                                                                                                                                                                                                                                                                                                       </label>
//                                                                                                                                                                                                                                                                                                                                                                                     <input className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-first-name" type="text" placeholder="Jane Doe"/>
//                                                                                                                                                                                                                                                                                                                                                                                                 </div>
//                                                                                                                                                                                                                                                                                                                                                                                                             <div className="w-full md:w-1/2 px-3">
//                                                                                                                                                                                                                                                                                                                                                                                                                           <label className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" htmlFor="grid-last-name">
//                                                                                                                                                                                                                                                                                                                                                                                                                                           姓氏
//                                                                                                                                                                                                                                                                                                                                                                                                                                                         </label>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <input className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-last-name" type="text" placeholder="Doe"/>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div className="flex flex-wrap -mx-3 mb-6">
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div className="w-full px-3">
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <label className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" htmlFor="grid-email">
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 邮箱
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </label>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <input className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-email" type="email" placeholder="example@example.com"/>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div className="flex flex-wrap -mx-3 mb-6">
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div className="w-full px-3">
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <label className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" htmlFor="grid-message">
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       消息
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </label>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <textarea className="no-resize appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 h-48" id="grid-message" placeholder="Type your message here..."></textarea>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div className="w-full">
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <button className="shadow bg-blue-500 hover:bg-blue-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="submit">
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             发送消息
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </button>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </form>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       );
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       export default App;
